name: diff_retinex_env
channels:
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.05.30
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.8.17
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - cudatoolkit=11.3
  - pytorch=1.10.1
  - torchvision=0.11.2
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - cmake==3.27.1
      - contourpy==1.1.0
      - cycler==0.11.0
      - debugpy==1.8.1
      - einops==0.6.1
      - filelock==3.12.2
      - fonttools==4.42.0
      - fsspec==2023.10.0
      - ftfy==6.1.1
      - future==0.18.3
      - grpcio==1.57.0
      - idna==3.4
      - imageio==2.31.5
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.4
      - lazy-loader==0.3
      - lit==16.0.6
      - lmdb==1.4.1
      - lpips==0.1.4
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mpmath==1.3.0
      - natsort==8.4.0
      - networkx==3.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - openai-clip==1.0.1
      - opencv-python==4.2.0.34
      - packaging==23.1
      - pillow==10.0.0
      - platformdirs==4.0.0
      - pooch==1.8.2
      - protobuf==3.20.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.4.1
      - scikit-image==0.17.1
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - setuptools==59.5.0
      - six==1.16.0
      - sympy==1.12
      - tensorboard==2.14.0
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - timm==0.9.12
      - tomli==2.0.1
      - tqdm==4.65.0
      - triton==2.0.0
      - typing-extensions==4.7.1
      - urllib3==1.26.16
      - wcwidth==0.2.6
      - werkzeug==2.3.7
      - yapf==0.40.2
      - zipp==3.16.2
